name: Build SecretLetter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore SecretLetter.slnx /p:WindowsAppSDKSelfContained=true /p:WindowsAppSDKVersion=1.5.240404000

    - name: Build solution
      run: dotnet build SecretLetter.slnx --configuration Release --no-restore

    - name: Publish UI project
      run: dotnet publish SecretLetter.UI/SecretLetter.UI.csproj -r win-x64 -c Release --self-contained false -o publish


